language: python

python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"

cache: pip
install:
  # - pip install -e '.[tests]'
  - pip install setuptools --upgrade; pip install -r test_requirements.txt; python setup.py install

script:
  - pytest tests
  - nosetests --with-coverage --cover-package=flask_cognito --with-timer
after_success: coveralls
